# Generated by Django 5.1.6 on 2025-02-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='certificates/')),
                ('category', models.CharField(choices=[('PROGRAMMING', 'Programming'), ('WEB_DEV', 'Web Development'), ('DATA_SCIENCE', 'Data Science'), ('CLOUD', 'Cloud Computing'), ('OTHER', 'Other')], max_length=50)),
                ('issuer', models.CharField(max_length=100)),
                ('issuer_logo', models.URLField()),
                ('credential_url', models.URLField()),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
