# Generated by Django 5.1.7 on 2025-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('SOFTWARE ', 'Software Proficiency'), ('TOOLS ', 'Electrical Testing Tool'), ('MAINTENANCE', 'Maintenance')], max_length=50),
        ),
    ]
