# Generated by Django 5.1.7 on 2025-03-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('SOFTWARE ', 'Software '), ('TOOLS ', ' Tool'), ('MAINTENANCE', 'Maintenance')], max_length=50),
        ),
    ]
