# Generated by Django 5.1.7 on 2025-03-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='place',
            field=models.CharField(default=15, max_length=200),
            preserve_default=False,
        ),
    ]
